[project]
name = "rasqal"
version = "0.1.5"
requires-python = ">=3.9"
description = "A dynamically executed quantum-classical hybrid optimizing runtime."
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python",
    "Programming Language :: Rust",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
]

authors = [
    { name = "John Dumbell", email = "euphoricEulogy@gmail.com" }
]

dependencies = [
    "qiskit==0.45.*,<1.0.0",
    "qiskit-optimization>=0.4.0",
    "qiskit-ignis>=0.7.0",
    "qiskit-aer>=0.13.0",
    "pytket>=1.23.0"
]

[project.urls]
Repository = "https://github.com/oqc-community/rasqal.git"
Issues = "https://github.com/oqc-community/rasqal/issues"

[build-system]
requires = ["maturin ~= 0.13.7"]
build-backend = "maturin"
