name: deploy-wheels

on:
  release:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    env: ${{ matrix.config.env }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            os: "ubuntu-20.04",
            arch: "amd64",
            target: "default",
            env: { },
          }
          - {
            os: "windows-2019",
            arch: "amd64",
            target: "default",
            env: { },
          }
          - {
            os: "macos-11",
            arch: "amd64",
            target: "default",
            env: {
              MACOSX_DEPLOYMENT_TARGET: 10.9
            },
          }
          - {
            os: "macos-14",
            arch: "aarch64",
            target: "default",
            env: { },
          }
    steps:
      - uses: actions/checkout@v4
      - name: Setup rust toolchain
        uses: ./.github/actions/rust-toolchain
        with:
          toolchain: 1.75.0
          components: rustfmt clippy
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
        if: ${{ matrix.config.os != 'macos-14' }}
      - name: Linux - Install build dependencies, ccache, ninja
        run: sudo apt-get install -y ccache ninja-build
        if: ${{ matrix.config.os == 'ubuntu-20.04' }}
      - name: Windows - Install build dependencies, sccache, ninja
        run: choco install --accept-license -y sccache ninja
        if: ${{ matrix.config.os == 'windows-2019' }}
      - name: MacOS - Install build dependencies, ccache, ninja
        run: brew install ccache ninja
        if: ${{ matrix.config.os == 'macos-11' }}
      - name: MacOS - Install build dependencies, ccache, ninja
        run: brew install ccache ninja
        if: ${{ matrix.config.os == 'macos-14' }}
      - name: Install LLVM
        uses: ./.github/actions/install-llvm
        with:
          version: "14"
          os: ${{ matrix.config.os }}
          directory: ${{ github.workspace }}/target/llvm
          target: ${{ matrix.config.target }}
      - name: "Build ${{ matrix.config.target }}"
        run: ./build.ps1 -t ${{ matrix.config.target }}
        shell: pwsh
      - name: Artifacts - manylinux
        uses: actions/upload-artifact@v4
        with:
          name: manylinux-artifacts
          path: target/wheels/*manylinux_2_*.whl
        if: ${{ matrix.config.os == 'ubuntu-20.04' }}
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.os }}-artifacts
          path: target/wheels/*
        if: ${{ matrix.config.os != 'ubuntu-20.04' }}

  publish:
    runs-on: ubuntu-latest
    needs: [ build ]
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist/

      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist/